version: '3.8'

services:
  nginx:
    build: ./nginx
    ports:
      - 1337:80
    depends_on:
      - credentials_manager
  credentials_manager:
    image: pavel3333/credentials_manager
    build: ./service
    command: gunicorn --bind 0.0.0.0:5000 --workers 4 manage:app
    volumes:
      - ./data:/home/CredentialsManager/service/data/
    expose:
      - 5000
    env_file:
      - ./.env.prod
