version: '3.8'

services:
  web:
    build: ./service
    command: python manage.py run -h 0.0.0.0
    volumes:
      - ./data:/usr/src/CredentialsManager/data/
    ports:
      - 5000:5000
    env_file:
      - ./.env.dev
