version: '3.8'

services:
  credentials_manager:
    image: pavel3333/credentials_manager
    build: ./service
    command: python manage.py run -h 0.0.0.0
    volumes:
      - ./data:/home/CredentialsManager/service/data/
    ports:
      - 5000:5000
    env_file:
      - ./.env.prod
